name: Learning GitHub Actions

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Git Branch
      run: git branch

    - name: Git fetch
      run: git fetch --all

    - name: Check Git log
      run: git log -n 3

    - name: Git Config
      run: |
        git config user.name ${{ secrets.NAME }}
        git config user.email ${{ secrets.EMAIL_ID }}

    - name: c1
      run: git checkout minNumOfSeatsToMoveEveryone

    - name: rebase
      run: |
        git fetch --all
        git rebase origin/main
        git push -f

    - name: Again Check Git log
      run: git log

    - name: Check Git Branch again
      run: git branch

    - name: Git config unset
      if: always()
      run: |
        git config --unset-all user.name
        git config --unset-all user.email